### PR TITLE
add fix for empty room

### LINKED ISSUE #72: Fix wrong room URL making server crash

### PR DESCRIPTION
**Pull request by adrien-nf**
Closes #72

### CODE REVIEW

File: server/classes/Storage/RoomStorage.ts [hunk 1]
```diff
@@ -16,14 +16,20 @@ export default class RoomStorage extends Storage<string, Room> {
...
 		
 		return room;
 	}
 	
 	removePlayer(id: string, player: Player): Room {
-		return this.get(id).removePlayer(player);
+		const room = this.get(id);
+		
+		if(room) {
+			room.removePlayer(player);
```
Comment (cyrilgourgouillon) [inline server/classes/Storage/RoomStorage.ts:30]: `room.remove(player)` to reduce redundancy ?

**Review by cyrilgourgouillon — APPROVED** [review]
